Affordable gemstone jewelry, over 1400 handmade designs, search by color, stone, beaded or non beaded in silver or non-silver and some gold plated silver (Vermeil).  We use real or genuine stones unless other wise specified.
We have been in business since 1997, <a href=http://www.alexa.com/data/details/?url=semiprecious.com>(check Alexa.com)</a>. Security:  We use paypal as well as send you to secure payment gateway: <a href=http://www.authorize.net>Authorize.net</a>.
You may also pay by e-check/check/money order after you fill your cart.

