<table width=750><tr><td width=750 align=center>
</td></tr></table>
<font color='black'>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr bgcolor="white" valign="top">
<td valign=top align='center' border=0>
<a href='detail.cfm?category=necklaces&newitem=499&price=29.0000&description=Silver%20and%20stone%20necklace%2E%2018g%20Stelring%20Silver%2C%2018%20inch%2E%20email%20for%20stone%20change&newitem=499&invent=10'>
<img src = "images/necklaces/thumb/499.jpg"  border='4' bordercolor='black'
   name="img499" alt="peridot,garnet,amethyst,citrine,labrodite necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$29.00</font></b><br><font face="Verdana" verdana size="1">Silver and stone necklace. 18g Stelring Silver, 18 inch. email for stone change</font><br>

<a href='detail.cfm?category=necklaces&newitem=499&price=29.0000&description=Silver%20and%20stone%20necklace%2E%2018g%20Stelring%20Silver%2C%2018%20inch%2E%20email%20for%20stone%20change&newitem=499&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=498&price=21.0000&description=Silver%20and%20stone%2E%20Custom%20order%204%20weeks%20delivery%2E%20Email%20stone%20desired&newitem=498&invent=10'>


<img src = "images/necklaces/thumb/498.jpg"  border='4' bordercolor='black'
 
  name="img498" alt="garnet,amethyst,citrine,moonstone,labrodite necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$21.00</font></b><br><font face="Verdana" verdana size="1">Silver and stone. Custom order 4 weeks delivery. Email stone desired</font><br>

<a href='detail.cfm?category=necklaces&newitem=498&price=21.0000&description=Silver%20and%20stone%2E%20Custom%20order%204%20weeks%20delivery%2E%20Email%20stone%20desired&newitem=498&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=497&price=17.0000&description=Silver%20and%20stone%2E%20Stones%20can%20be%20changed%20on%20request%20by%20email%2E%204%20WEEK%20DELIVERY&newitem=497&invent=10'>


<img src = "images/necklaces/thumb/497.jpg"  border='4' bordercolor='black'
 
  name="img497" alt="garnet,peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$17.00</font></b><br><font face="Verdana" verdana size="1">Silver and stone. Stones can be changed on request by email. 4 WEEK DELIVERY</font><br>

<a href='detail.cfm?category=necklaces&newitem=497&price=17.0000&description=Silver%20and%20stone%2E%20Stones%20can%20be%20changed%20on%20request%20by%20email%2E%204%20WEEK%20DELIVERY&newitem=497&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=496&price=32.0000&description=Silver%20and%20stone%20%28request%20stone%20desired%20by%20email%29%2E%2020g%20high%20quality%20silver%2E&newitem=496&invent=10'>


<img src = "images/necklaces/thumb/496.jpg"  border='4' bordercolor='black'
 
  name="img496" alt="garnet,amethyst,peridot,onyx,quartz,citrine necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$32.00</font></b><br><font face="Verdana" verdana size="1">Silver and stone (request stone desired by email). 20g high quality silver.</font><br>

<a href='detail.cfm?category=necklaces&newitem=496&price=32.0000&description=Silver%20and%20stone%20%28request%20stone%20desired%20by%20email%29%2E%2020g%20high%20quality%20silver%2E&newitem=496&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=495&price=45.0000&saleprice=29.0000&description=Peridot%20and%20silver%20necklace%20%2820%20g%29%2E%20THIS%20IS%20A%204%20WEEK%20DELIVERY%2E%20Made%20on%20order%2E%20Stone%20can%20be%20changed%20to%20any%20by%20email&newitem=495&invent=10'>


<img src = "images/necklaces/thumb/495.jpg"  border='4' bordercolor='black'
 
  name="img495" alt="Peridot necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$29.00</B>&nbsp;Regular
<b><font color="#000080">$45.00</font></b><br><font face="Verdana" verdana size="1">Peridot and silver necklace (20 g). THIS IS A 4 WEEK DELIVERY. Made on order. Stone can be changed to any by email</font><br>

<a href='detail.cfm?category=Necklaces&newitem=495&price=45.0000&saleprice=29.0000&description=Peridot%20and%20silver%20necklace%20%2820%20g%29%2E%20THIS%20IS%20A%204%20WEEK%20DELIVERY%2E%20Made%20on%20order%2E%20Stone%20can%20be%20changed%20to%20any%20by%20email&newitem=495&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=494&price=25.0000&description=Sterling%20Silver%20and%20Semiprecious%20stone%20necklace%2E%2016%20g%2E%20THIS%20IS%20A%204%20WEEK%20DELIVERY%2C%20made%20on%20order%2E%20Stones%20can%20be%20customized%20on%20request&newitem=494&invent=10'>


<img src = "images/necklaces/thumb/494.jpg"  border='4' bordercolor='black'
 
  name="img494" alt="amethyst,garnet,citrine necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$25.00</font></b><br><font face="Verdana" verdana size="1">Sterling Silver and Semiprecious stone necklace. 16 g. THIS IS A 4 WEEK DELIVERY, made on order. Stones can be customized on request</font><br>

<a href='detail.cfm?category=necklaces&newitem=494&price=25.0000&description=Sterling%20Silver%20and%20Semiprecious%20stone%20necklace%2E%2016%20g%2E%20THIS%20IS%20A%204%20WEEK%20DELIVERY%2C%20made%20on%20order%2E%20Stones%20can%20be%20customized%20on%20request&newitem=494&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=487&price=18.0000&description=Garnet%20necklace%20with%20a%20well%20cut%20garnet%20pendant%20set%20in%20sterling%20silver&newitem=487&invent=3'>


<img src = "images/necklaces/thumb/487.jpg"  border='4' bordercolor='black'
 
  name="img487" alt="garnet necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Garnet necklace with a well cut garnet pendant set in sterling silver</font><br>

<a href='detail.cfm?category=necklaces&newitem=487&price=18.0000&description=Garnet%20necklace%20with%20a%20well%20cut%20garnet%20pendant%20set%20in%20sterling%20silver&newitem=487&invent=3'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=486&price=19.0000&description=Another%20pretty%20moss%20agate%20necklace%2C%2024%20inch%2E%20Only%20one%20left%2E&newitem=486&invent=1'>


<img src = "images/necklaces/thumb/486.jpg"  border='4' bordercolor='black'
 
  name="img486" alt="moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$19.00</font></b><br><font face="Verdana" verdana size="1">Another pretty moss agate necklace, 24 inch. Only one left.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=486&price=19.0000&description=Another%20pretty%20moss%20agate%20necklace%2C%2024%20inch%2E%20Only%20one%20left%2E&newitem=486&invent=1'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=485&price=22.0000&description=Awesome%20moss%20agate%20necklace%2E%20Only%20one%20left%2E%2024%20inches&newitem=485&invent=1'>


<img src = "images/necklaces/thumb/485.jpg"  border='4' bordercolor='black'
 
  name="img485" alt="moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$22.00</font></b><br><font face="Verdana" verdana size="1">Awesome moss agate necklace. Only one left. 24 inches</font><br>

<a href='detail.cfm?category=Necklaces&newitem=485&price=22.0000&description=Awesome%20moss%20agate%20necklace%2E%20Only%20one%20left%2E%2024%20inches&newitem=485&invent=1'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=484&price=12.0000&description=Tiger%20eye%20necklace%2C%2017%20inch%2C%20knotted%20between%20beads%2E%20Lifetime%20necklace%2E&newitem=484&invent=5'>


<img src = "images/necklaces/thumb/484.jpg"  border='4' bordercolor='black'
 
  name="img484" alt="tiger eye necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye necklace, 17 inch, knotted between beads. Lifetime necklace.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=484&price=12.0000&description=Tiger%20eye%20necklace%2C%2017%20inch%2C%20knotted%20between%20beads%2E%20Lifetime%20necklace%2E&newitem=484&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=483&price=18.0000&saleprice=12.0000&description=tiger%20eye%20necklace%20with%20spiral%20cut%20and%20knotted%20between%20beads%2C%2024%20inch&newitem=483&invent=5'>


<img src = "images/necklaces/thumb/483.jpg"  border='4' bordercolor='black'
 
  name="img483" alt="tiger eye necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$12.00</B>&nbsp;Regular
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">tiger eye necklace with spiral cut and knotted between beads, 24 inch</font><br>

<a href='detail.cfm?category=Necklaces&newitem=483&price=18.0000&saleprice=12.0000&description=tiger%20eye%20necklace%20with%20spiral%20cut%20and%20knotted%20between%20beads%2C%2024%20inch&newitem=483&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=482&price=16.0000&saleprice=8.9000&description=Tiger%20eye%20necklace%20with%20blue%20goldstone%20and%20ethnic%20balls%2E%2017%20inches%2E&newitem=482&invent=5'>


<img src = "images/necklaces/thumb/482.jpg"  border='4' bordercolor='black'
 
  name="img482" alt="tiger eye necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$8.90</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye necklace with blue goldstone and ethnic balls. 17 inches.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=482&price=16.0000&saleprice=8.9000&description=Tiger%20eye%20necklace%20with%20blue%20goldstone%20and%20ethnic%20balls%2E%2017%20inches%2E&newitem=482&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=481&price=15.0000&saleprice=8.9000&description=Tiger%20eye%20necklace%2C%2017%20inch%2C%20spiral%20cut%20and%20ethnic%20balls%2E%20Looks%20awesome&newitem=481&invent=5'>


<img src = "images/necklaces/thumb/481.jpg"  border='4' bordercolor='black'
 
  name="img481" alt="tiger eye necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$8.90</B>&nbsp;Regular
<b><font color="#000080">$15.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye necklace, 17 inch, spiral cut and ethnic balls. Looks awesome</font><br>

<a href='detail.cfm?category=Necklaces&newitem=481&price=15.0000&saleprice=8.9000&description=Tiger%20eye%20necklace%2C%2017%20inch%2C%20spiral%20cut%20and%20ethnic%20balls%2E%20Looks%20awesome&newitem=481&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=480&price=18.0000&description=Awesome%20tiger%20eye%20necklace%20with%20simulated%20bone%20craved%20piece%2E%2017%20inches&newitem=480&invent=1'>


<img src = "images/necklaces/thumb/480.jpg"  border='4' bordercolor='black'
 
  name="img480" alt="tiger eye necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Awesome tiger eye necklace with simulated bone craved piece. 17 inches</font><br>

<a href='detail.cfm?category=necklaces&newitem=480&price=18.0000&description=Awesome%20tiger%20eye%20necklace%20with%20simulated%20bone%20craved%20piece%2E%2017%20inches&newitem=480&invent=1'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Sets&newitem=475&price=130.0000&description=Sterling%20silver%2C%20turquoise%20and%20amber%20necklace%20with%20Bali%20beads&newitem=475&invent=4'>


<img src = "images/necklaces/thumb/475.jpg"  border='4' bordercolor='black'
 
  name="img475" alt="turquoise necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$130.00</font></b><br><font face="Verdana" verdana size="1">Sterling silver, turquoise and amber necklace with Bali beads</font><br>

<a href='detail.cfm?category=Sets&newitem=475&price=130.0000&description=Sterling%20silver%2C%20turquoise%20and%20amber%20necklace%20with%20Bali%20beads&newitem=475&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=469&price=14.0000&saleprice=11.0000&description=A%20very%20beautiful%20agate%2C%20with%20various%20shades%20and%20reflections%2E%2024%20inch%2E&newitem=469&invent=5'>


<img src = "images/necklaces/thumb/469.jpg"  border='4' bordercolor='black'
 
  name="img469" alt="Agate necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$11.00</B>&nbsp;Regular
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">A very beautiful agate, with various shades and reflections. 24 inch.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=469&price=14.0000&saleprice=11.0000&description=A%20very%20beautiful%20agate%2C%20with%20various%20shades%20and%20reflections%2E%2024%20inch%2E&newitem=469&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=468&price=28.0000&description=Nice%20clear%20button%20shaped%20beads%20in%20this%2024%20inch%20citrine%20necklace%2E&newitem=468&invent=5'>


<img src = "images/necklaces/thumb/468.jpg"  border='4' bordercolor='black'
 
  name="img468" alt="Citrine necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$28.00</font></b><br><font face="Verdana" verdana size="1">Nice clear button shaped beads in this 24 inch citrine necklace.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=468&price=28.0000&description=Nice%20clear%20button%20shaped%20beads%20in%20this%2024%20inch%20citrine%20necklace%2E&newitem=468&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=467&price=15.0000&description=Tiger%20eye%2C%20garnet%2C%20amethyst%20and%20carnelian%20necklace%20with%20golden%20rings%2E%2017%20inch&newitem=467&invent=4'>


<img src = "images/necklaces/thumb/467.jpg"  border='4' bordercolor='black'
 
  name="img467" alt="mixed stones necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$15.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye, garnet, amethyst and carnelian necklace with golden rings. 17 inch</font><br>

<a href='detail.cfm?category=Necklaces&newitem=467&price=15.0000&description=Tiger%20eye%2C%20garnet%2C%20amethyst%20and%20carnelian%20necklace%20with%20golden%20rings%2E%2017%20inch&newitem=467&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=466&price=16.0000&description=Multi%2Dfaceted%20cut%20beads%20in%20the%20pretty%20peridot%20necklace%2C%2024%20inch&newitem=466&invent=5'>


<img src = "images/necklaces/thumb/466.jpg"  border='4' bordercolor='black'
 
  name="img466" alt="peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Multi-faceted cut beads in the pretty peridot necklace, 24 inch</font><br>

<a href='detail.cfm?category=Necklaces&newitem=466&price=16.0000&description=Multi%2Dfaceted%20cut%20beads%20in%20the%20pretty%20peridot%20necklace%2C%2024%20inch&newitem=466&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=465&price=14.0000&description=Multi%2Dfaceted%20cut%20peridot%20necklace%2E%2017%20inch%2E&newitem=465&invent=5'>


<img src = "images/necklaces/thumb/465.jpg"  border='4' bordercolor='black'
 
  name="img465" alt="peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">Multi-faceted cut peridot necklace. 17 inch.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=465&price=14.0000&description=Multi%2Dfaceted%20cut%20peridot%20necklace%2E%2017%20inch%2E&newitem=465&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=464&price=17.0000&description=Pretty%20moss%20agate%20necklace%2C%20plant%20like%20inclusions%2E%20Knotted%20between%20beads%2E%2017%20inches%2E&newitem=464&invent=5'>


<img src = "images/necklaces/thumb/464.jpg"  border='4' bordercolor='black'
 
  name="img464" alt="moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$17.00</font></b><br><font face="Verdana" verdana size="1">Pretty moss agate necklace, plant like inclusions. Knotted between beads. 17 inches.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=464&price=17.0000&description=Pretty%20moss%20agate%20necklace%2C%20plant%20like%20inclusions%2E%20Knotted%20between%20beads%2E%2017%20inches%2E&newitem=464&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=462&price=7.0000&description=Aventurine%20and%20carnelian%20necklace%20with%20golden%20rings%2C%2017%20inch%2E&newitem=462&invent=5'>


<img src = "images/necklaces/thumb/462.jpg"  border='4' bordercolor='black'
 
  name="img462" alt="carnelian necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$7.00</font></b><br><font face="Verdana" verdana size="1">Aventurine and carnelian necklace with golden rings, 17 inch.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=462&price=7.0000&description=Aventurine%20and%20carnelian%20necklace%20with%20golden%20rings%2C%2017%20inch%2E&newitem=462&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=461&price=18.0000&description=Mult%2Dcolored%20tourmaline%20neacklace%20in%20a%20nice%20clasp%2E%2024%20inch%2E&newitem=461&invent=5'>


<img src = "images/necklaces/thumb/461.jpg"  border='4' bordercolor='black'
 
  name="img461" alt="Tourmaline necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Mult-colored tourmaline neacklace in a nice clasp. 24 inch.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=461&price=18.0000&description=Mult%2Dcolored%20tourmaline%20neacklace%20in%20a%20nice%20clasp%2E%2024%20inch%2E&newitem=461&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=460&price=19.0000&description=Amethyst%20necaklce%20with%20a%20pendant%20set%20in%20silver%2E%20Beads%20are%20multi%2Dfacet%20cut%2C%20multiplying%20the%20shine%2E&newitem=460&invent=5'>


<img src = "images/necklaces/thumb/460.jpg"  border='4' bordercolor='black'
 
  name="img460" alt="amethyst necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$19.00</font></b><br><font face="Verdana" verdana size="1">Amethyst necaklce with a pendant set in silver. Beads are multi-facet cut, multiplying the shine.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=460&price=19.0000&description=Amethyst%20necaklce%20with%20a%20pendant%20set%20in%20silver%2E%20Beads%20are%20multi%2Dfacet%20cut%2C%20multiplying%20the%20shine%2E&newitem=460&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=458&price=6.0000&description=Heart%20shaped%20pendant%20hematite%20necklace%2E%2017%20inch&newitem=458&invent=10'>


<img src = "images/necklaces/thumb/458.jpg"  border='4' bordercolor='black'
 
  name="img458" alt="Hematite necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$6.00</font></b><br><font face="Verdana" verdana size="1">Heart shaped pendant hematite necklace. 17 inch</font><br>

<a href='detail.cfm?category=Necklaces&newitem=458&price=6.0000&description=Heart%20shaped%20pendant%20hematite%20necklace%2E%2017%20inch&newitem=458&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=456&price=8.0000&description=Oval%20shaped%20hematite%20pendant%20necklace%2E&newitem=456&invent=10'>


<img src = "images/necklaces/thumb/456.jpg"  border='4' bordercolor='black'
 
  name="img456" alt="hematite necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$8.00</font></b><br><font face="Verdana" verdana size="1">Oval shaped hematite pendant necklace.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=456&price=8.0000&description=Oval%20shaped%20hematite%20pendant%20necklace%2E&newitem=456&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=455&price=12.0000&description=Nice%2C%20lusturous%20hematite%20necklace%2017%20inches%2E&newitem=455&invent=5'>


<img src = "images/necklaces/thumb/455.jpg"  border='4' bordercolor='black'
 
  name="img455" alt="hematite necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Nice, lusturous hematite necklace 17 inches.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=455&price=12.0000&description=Nice%2C%20lusturous%20hematite%20necklace%2017%20inches%2E&newitem=455&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=454&price=32.0000&description=Multi%2Dfaceted%20cut%2024%20inch%20citrine%20%28topaz%29%20necklace%2E&newitem=454&invent=7'>


<img src = "images/necklaces/thumb/454.jpg"  border='4' bordercolor='black'
 
  name="img454" alt="Citrine necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$32.00</font></b><br><font face="Verdana" verdana size="1">Multi-faceted cut 24 inch citrine (topaz) necklace.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=454&price=32.0000&description=Multi%2Dfaceted%20cut%2024%20inch%20citrine%20%28topaz%29%20necklace%2E&newitem=454&invent=7'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=453&price=26.0000&saleprice=16.0000&description=Light%20clear%20amethyst%20necklace%20with%20carved%20beads%2E%2024%20inch%2C%20knotted%2E%20Excellent%20quality%20stones%2E%20&newitem=453&invent=10'>


<img src = "images/necklaces/thumb/453.jpg"  border='4' bordercolor='black'
 
  name="img453" alt="Amethyst necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$16.00</B>&nbsp;Regular
<b><font color="#000080">$26.00</font></b><br><font face="Verdana" verdana size="1">Light clear amethyst necklace with carved beads. 24 inch, knotted. Excellent quality stones. </font><br>

<a href='detail.cfm?category=Necklaces&newitem=453&price=26.0000&saleprice=16.0000&description=Light%20clear%20amethyst%20necklace%20with%20carved%20beads%2E%2024%20inch%2C%20knotted%2E%20Excellent%20quality%20stones%2E%20&newitem=453&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=452&price=35.0000&description=Lapis%20Lazuli%20necklace%2C%2017%20in%20knotted%2E%20Beautiful%20large%20button%20shaped%20stones%2E%20Vary%20in%20size%20from%20top%20to&newitem=452&invent=5'>


<img src = "images/necklaces/thumb/452.jpg"  border='4' bordercolor='black'
 
  name="img452" alt="Lapis Lazuli necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$35.00</font></b><br><font face="Verdana" verdana size="1">Lapis Lazuli necklace, 17 in knotted. Beautiful large button shaped stones. Vary in size from top to</font><br>

<a href='detail.cfm?category=Necklaces&newitem=452&price=35.0000&description=Lapis%20Lazuli%20necklace%2C%2017%20in%20knotted%2E%20Beautiful%20large%20button%20shaped%20stones%2E%20Vary%20in%20size%20from%20top%20to&newitem=452&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=451&price=16.0000&saleprice=9.0000&description=Lapis%20lazuli%20and%20tiger%20eye%20necklace%20with%20golden%20rings%2017%20inch%2E%20Stone%20combination%20rarely%20found%2E&newitem=451&invent=10'>


<img src = "images/necklaces/thumb/451.jpg"  border='4' bordercolor='black'
 
  name="img451" alt="tiger eye,lapis lazuli necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$9.00</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Lapis lazuli and tiger eye necklace with golden rings 17 inch. Stone combination rarely found.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=451&price=16.0000&saleprice=9.0000&description=Lapis%20lazuli%20and%20tiger%20eye%20necklace%20with%20golden%20rings%2017%20inch%2E%20Stone%20combination%20rarely%20found%2E&newitem=451&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=450&price=25.0000&description=Pearl%20and%20shaded%20pearl%2E%20Picture%20says%20a%20thousand%20words%20here%2E%20Lovely%21&newitem=450&invent=5'>


<img src = "images/necklaces/thumb/450.jpg"  border='4' bordercolor='black'
 
  name="img450" alt="pearl necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$25.00</font></b><br><font face="Verdana" verdana size="1">Pearl and shaded pearl. Picture says a thousand words here. Lovely!</font><br>

<a href='detail.cfm?category=Necklaces&newitem=450&price=25.0000&description=Pearl%20and%20shaded%20pearl%2E%20Picture%20says%20a%20thousand%20words%20here%2E%20Lovely%21&newitem=450&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=449&price=18.0000&description=Button%20oblong%20bead%20peridot%20necklace%2E%20This%20shape%20shines%20in%20all%20directions%2E&newitem=449&invent=3'>


<img src = "images/necklaces/thumb/449.jpg"  border='4' bordercolor='black'
 
  name="img449" alt="peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Button oblong bead peridot necklace. This shape shines in all directions.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=449&price=18.0000&description=Button%20oblong%20bead%20peridot%20necklace%2E%20This%20shape%20shines%20in%20all%20directions%2E&newitem=449&invent=3'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=448&price=23.0000&description=Lapis%20Lazuli%20silver%20pendant%20with%20lapis%20lazuli%20necklace%2E%20What%20a%20unique%20buy%2E%20The%20cuts%20are%20fancy&newitem=448&invent=10'>


<img src = "images/necklaces/thumb/448.jpg"  border='4' bordercolor='black'
 
  name="img448" alt="lapis lazuli necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$23.00</font></b><br><font face="Verdana" verdana size="1">Lapis Lazuli silver pendant with lapis lazuli necklace. What a unique buy. The cuts are fancy</font><br>

<a href='detail.cfm?category=Necklaces&newitem=448&price=23.0000&description=Lapis%20Lazuli%20silver%20pendant%20with%20lapis%20lazuli%20necklace%2E%20What%20a%20unique%20buy%2E%20The%20cuts%20are%20fancy&newitem=448&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=447&price=18.5000&description=Pearl%20and%20Lapis%20lazuli%20necklace%2017%20inch%2E%20Outstanding%2C%20great%20cut%2C%20good%20price%2E&newitem=447&invent=10'>


<img src = "images/necklaces/thumb/447.jpg"  border='4' bordercolor='black'
 
  name="img447" alt="lapis lazuli,pearl necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.50</font></b><br><font face="Verdana" verdana size="1">Pearl and Lapis lazuli necklace 17 inch. Outstanding, great cut, good price.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=447&price=18.5000&description=Pearl%20and%20Lapis%20lazuli%20necklace%2017%20inch%2E%20Outstanding%2C%20great%20cut%2C%20good%20price%2E&newitem=447&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=446&price=19.0000&description=Pearl%20and%20garnet%20necklace%20spherical%20beads%20with%20golden%20rings%2E%20%20Double%20strand%2E&newitem=446&invent=1'>


<img src = "images/necklaces/thumb/446.jpg"  border='4' bordercolor='black'
 
  name="img446" alt="pearl,garnet necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$19.00</font></b><br><font face="Verdana" verdana size="1">Pearl and garnet necklace spherical beads with golden rings.  Double strand.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=446&price=19.0000&description=Pearl%20and%20garnet%20necklace%20spherical%20beads%20with%20golden%20rings%2E%20%20Double%20strand%2E&newitem=446&invent=1'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=445&price=12.5000&saleprice=9.0000&description=Pearl%20and%20Peridot%20necklace%2017%20inch%2E%20&newitem=445&invent=10'>


<img src = "images/necklaces/thumb/445.jpg"  border='4' bordercolor='black'
 
  name="img445" alt="peridot,pearl necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$9.00</B>&nbsp;Regular
<b><font color="#000080">$12.50</font></b><br><font face="Verdana" verdana size="1">Pearl and Peridot necklace 17 inch. </font><br>

<a href='detail.cfm?category=Necklaces&newitem=445&price=12.5000&saleprice=9.0000&description=Pearl%20and%20Peridot%20necklace%2017%20inch%2E%20&newitem=445&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=444&price=16.0000&saleprice=9.8000&description=Pearl%20and%20citrine%20%28topaz%29%20necklace%2017%20inch%2E%20Triangular%20citrine%20beads%2E%20Nice%20as%20you%20can%20see&newitem=444&invent=10'>


<img src = "images/necklaces/thumb/444.jpg"  border='4' bordercolor='black'
 
  name="img444" alt="citrine,topaz necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$9.80</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Pearl and citrine (topaz) necklace 17 inch. Triangular citrine beads. Nice as you can see</font><br>

<a href='detail.cfm?category=Necklaces&newitem=444&price=16.0000&saleprice=9.8000&description=Pearl%20and%20citrine%20%28topaz%29%20necklace%2017%20inch%2E%20Triangular%20citrine%20beads%2E%20Nice%20as%20you%20can%20see&newitem=444&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=443&price=9.0000&description=Peridot%20necklace%2017%20inch%2E%20Leaf%20%2F%20heart%20shaped%20beads%2E&newitem=443&invent=10'>


<img src = "images/necklaces/thumb/443.jpg"  border='4' bordercolor='black'
 
  name="img443" alt="peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$9.00</font></b><br><font face="Verdana" verdana size="1">Peridot necklace 17 inch. Leaf / heart shaped beads.</font><br>

<a href='detail.cfm?category=necklaces&newitem=443&price=9.0000&description=Peridot%20necklace%2017%20inch%2E%20Leaf%20%2F%20heart%20shaped%20beads%2E&newitem=443&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=441&price=16.0000&saleprice=10.5000&description=pearl%20and%20Moss%20agate%20necklace%2017%20inch%2C%20a%20wonderful%20stone%2C%20with%20pearl%20it%20gives%20a%20wintery%20feel&newitem=441&invent=10'>


<img src = "images/necklaces/thumb/441.jpg"  border='4' bordercolor='black'
 
  name="img441" alt="moss agate,pearl necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$10.50</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">pearl and Moss agate necklace 17 inch, a wonderful stone, with pearl it gives a wintery feel</font><br>

<a href='detail.cfm?category=necklaces&newitem=441&price=16.0000&saleprice=10.5000&description=pearl%20and%20Moss%20agate%20necklace%2017%20inch%2C%20a%20wonderful%20stone%2C%20with%20pearl%20it%20gives%20a%20wintery%20feel&newitem=441&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=440&price=16.0000&saleprice=8.0000&description=Sparkling%20Goldstone%20and%20Pearl%20necklace%2017%20inch%2E%20Under%20yellow%20light%20sparkles%20with%20hundreds%20of%20inclusi&newitem=440&invent=10'>


<img src = "images/necklaces/thumb/440.jpg"  border='4' bordercolor='black'
 
  name="img440" alt="goldstone,pearl necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$8.00</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Sparkling Goldstone and Pearl necklace 17 inch. Under yellow light sparkles with hundreds of inclusi</font><br>

<a href='detail.cfm?category=necklaces&newitem=440&price=16.0000&saleprice=8.0000&description=Sparkling%20Goldstone%20and%20Pearl%20necklace%2017%20inch%2E%20Under%20yellow%20light%20sparkles%20with%20hundreds%20of%20inclusi&newitem=440&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=431&price=23.5600&description=24%20inch%2Cpure%20crystal%2C%20nice%20quality%20rose%20quartz%20necklace%2E&newitem=431&invent=10'>


<img src = "images/necklaces/thumb/431.jpg"  border='4' bordercolor='black'
 
  name="img431" alt="rose quartz necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$23.56</font></b><br><font face="Verdana" verdana size="1">24 inch,pure crystal, nice quality rose quartz necklace.</font><br>

<a href='detail.cfm?category=necklaces&newitem=431&price=23.5600&description=24%20inch%2Cpure%20crystal%2C%20nice%20quality%20rose%20quartz%20necklace%2E&newitem=431&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=430&price=18.7000&description=24%20inch%20peridot%20necklace%2E%20Clear%20light%20green%20crystal%2E&newitem=430&invent=3'>


<img src = "images/necklaces/thumb/430.jpg"  border='4' bordercolor='black'
 
  name="img430" alt="Peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.70</font></b><br><font face="Verdana" verdana size="1">24 inch peridot necklace. Clear light green crystal.</font><br>

<a href='detail.cfm?category=necklaces&newitem=430&price=18.7000&description=24%20inch%20peridot%20necklace%2E%20Clear%20light%20green%20crystal%2E&newitem=430&invent=3'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=429&price=16.0000&description=Carnelian%20necklace%20with%20a%20carnelian%20in%20silver%20pendant%2E%2017%20inch%2E%20&newitem=429&invent=6'>


<img src = "images/necklaces/thumb/429.jpg"  border='4' bordercolor='black'
 
  name="img429" alt="carnelian necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Carnelian necklace with a carnelian in silver pendant. 17 inch. </font><br>

<a href='detail.cfm?category=necklaces&newitem=429&price=16.0000&description=Carnelian%20necklace%20with%20a%20carnelian%20in%20silver%20pendant%2E%2017%20inch%2E%20&newitem=429&invent=6'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=427&price=29.0000&saleprice=14.9900&description=All%20kinds%20of%20semiprecious%20stone%20beads%20in%20this%2017%20in%2E%20necklace%20too%21%20Carnealian%2C%20lapis%2Cgoldstone%2Cameth&newitem=427&invent=10'>


<img src = "images/necklaces/thumb/427.jpg"  border='4' bordercolor='black'
 
  name="img427" alt="mixed stones,amethyst,tiger eye,carnelian necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$14.99</B>&nbsp;Regular
<b><font color="#000080">$29.00</font></b><br><font face="Verdana" verdana size="1">All kinds of semiprecious stone beads in this 17 in. necklace too! Carnealian, lapis,goldstone,ameth</font><br>

<a href='detail.cfm?category=necklaces&newitem=427&price=29.0000&saleprice=14.9900&description=All%20kinds%20of%20semiprecious%20stone%20beads%20in%20this%2017%20in%2E%20necklace%20too%21%20Carnealian%2C%20lapis%2Cgoldstone%2Cameth&newitem=427&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=426&price=24.8000&description=Only%20one%20left%21%20Very%20unique%2017%20inch%2E%20%20necklace%2E&newitem=426&invent=4'>


<img src = "images/necklaces/thumb/426.jpg"  border='4' bordercolor='black'
 
  name="img426" alt="mixed stones necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$24.80</font></b><br><font face="Verdana" verdana size="1">Only one left! Very unique 17 inch.  necklace.</font><br>

<a href='detail.cfm?category=necklaces&newitem=426&price=24.8000&description=Only%20one%20left%21%20Very%20unique%2017%20inch%2E%20%20necklace%2E&newitem=426&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=425&price=14.0000&saleprice=7.0000&description=Awesome%20ethnic%20balls%20make%20this%20simple%2017%20in%2E%20beaded%20necklace%20unique%20and%20attractive%2E&newitem=425&invent=2'>


<img src = "images/necklaces/thumb/425.jpg"  border='4' bordercolor='black'
 
  name="img425" alt="rose quartz necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$7.00</B>&nbsp;Regular
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">Awesome ethnic balls make this simple 17 in. beaded necklace unique and attractive.</font><br>

<a href='detail.cfm?category=necklaces&newitem=425&price=14.0000&saleprice=7.0000&description=Awesome%20ethnic%20balls%20make%20this%20simple%2017%20in%2E%20beaded%20necklace%20unique%20and%20attractive%2E&newitem=425&invent=2'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=424&price=14.9900&description=17%20inch%20Pearl%20and%20Peridot%20necklace%2E%20Price%20reduced%20for%20a%20short%20time%21&newitem=424&invent=2'>


<img src = "images/necklaces/thumb/424.jpg"  border='4' bordercolor='black'
 
  name="img424" alt="Peridot,pearl necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$14.99</font></b><br><font face="Verdana" verdana size="1">17 inch Pearl and Peridot necklace. Price reduced for a short time!</font><br>

<a href='detail.cfm?category=necklaces&newitem=424&price=14.9900&description=17%20inch%20Pearl%20and%20Peridot%20necklace%2E%20Price%20reduced%20for%20a%20short%20time%21&newitem=424&invent=2'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=423&price=11.9000&description=Blue%20goldstone%2FBlue%20sandstone%20and%20Carnelian%20necklace%20with%20pearl&newitem=423&invent=6'>


<img src = "images/necklaces/thumb/423.jpg"  border='4' bordercolor='black'
 
  name="img423" alt="Goldstone,pearl necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$11.90</font></b><br><font face="Verdana" verdana size="1">Blue goldstone/Blue sandstone and Carnelian necklace with pearl</font><br>

<a href='detail.cfm?category=necklaces&newitem=423&price=11.9000&description=Blue%20goldstone%2FBlue%20sandstone%20and%20Carnelian%20necklace%20with%20pearl&newitem=423&invent=6'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=418&price=14.0000&description=Garnet%20necklace%2C%2017%20inch%2C%20knotted%20between%20beads%2E&newitem=418&invent=5'>


<img src = "images/necklaces/thumb/418.jpg"  border='4' bordercolor='black'
 
  name="img418" alt="garnet necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">Garnet necklace, 17 inch, knotted between beads.</font><br>

<a href='detail.cfm?category=necklaces&newitem=418&price=14.0000&description=Garnet%20necklace%2C%2017%20inch%2C%20knotted%20between%20beads%2E&newitem=418&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=416&price=27.0000&saleprice=15.0000&description=Beautiful%20iolite%20and%20pearl%203%20strand%20necklace%2E%20&newitem=416&invent=4'>


<img src = "images/necklaces/thumb/416.jpg"  border='4' bordercolor='black'
 
  name="img416" alt="amethyst,pearl necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$15.00</B>&nbsp;Regular
<b><font color="#000080">$27.00</font></b><br><font face="Verdana" verdana size="1">Beautiful iolite and pearl 3 strand necklace. </font><br>

<a href='detail.cfm?category=necklaces&newitem=416&price=27.0000&saleprice=15.0000&description=Beautiful%20iolite%20and%20pearl%203%20strand%20necklace%2E%20&newitem=416&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=415&price=29.0000&description=Moss%20agate%20and%20pearl%20mult%2Dstrand%20necklace%2C%2017%20inches%2E%20Moss%20agate%20has%20plant%20%28moss%29%20like%20inclusions%20in&newitem=415&invent=4'>


<img src = "images/necklaces/thumb/415.jpg"  border='4' bordercolor='black'
 
  name="img415" alt="pearl,moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$29.00</font></b><br><font face="Verdana" verdana size="1">Moss agate and pearl mult-strand necklace, 17 inches. Moss agate has plant (moss) like inclusions in</font><br>

<a href='detail.cfm?category=necklaces&newitem=415&price=29.0000&description=Moss%20agate%20and%20pearl%20mult%2Dstrand%20necklace%2C%2017%20inches%2E%20Moss%20agate%20has%20plant%20%28moss%29%20like%20inclusions%20in&newitem=415&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=414&price=42.0000&saleprice=22.0000&description=Multi%2Dstone%203%20strand%20necklace%2E%20Extremely%20unique%2E%20Impressive%2C%20our%20favorite%2E&newitem=414&invent=10'>


<img src = "images/necklaces/thumb/414.jpg"  border='4' bordercolor='black'
 
  name="img414" alt="tiger eye,amethyst,garnet,citrine necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$22.00</B>&nbsp;Regular
<b><font color="#000080">$42.00</font></b><br><font face="Verdana" verdana size="1">Multi-stone 3 strand necklace. Extremely unique. Impressive, our favorite.</font><br>

<a href='detail.cfm?category=necklaces&newitem=414&price=42.0000&saleprice=22.0000&description=Multi%2Dstone%203%20strand%20necklace%2E%20Extremely%20unique%2E%20Impressive%2C%20our%20favorite%2E&newitem=414&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=412&price=21.0000&description=Pink%20agate%20with%20ethnic%20silver%20beads%20%28not%20real%20silver%29%2C%2017%20inch&newitem=412&invent=6'>


<img src = "images/necklaces/thumb/412.jpg"  border='4' bordercolor='black'
 
  name="img412" alt="agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$21.00</font></b><br><font face="Verdana" verdana size="1">Pink agate with ethnic silver beads (not real silver), 17 inch</font><br>

<a href='detail.cfm?category=necklaces&newitem=412&price=21.0000&description=Pink%20agate%20with%20ethnic%20silver%20beads%20%28not%20real%20silver%29%2C%2017%20inch&newitem=412&invent=6'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=390&price=20.0000&description=Jasper%20and%20bone%20choker%2C%2016%22%20and%20bracelet%2C%207%2E5%22%20set%2C%20unique%20elephant%20design%21%20&newitem=390&invent=10'>


<img src = "images/necklaces/thumb/390.jpg"  border='4' bordercolor='black'
 
  name="img390" alt="jasper necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$20.00</font></b><br><font face="Verdana" verdana size="1">Jasper and bone choker, 16" and bracelet, 7.5" set, unique elephant design! </font><br>

<a href='detail.cfm?category=Necklaces&newitem=390&price=20.0000&description=Jasper%20and%20bone%20choker%2C%2016%22%20and%20bracelet%2C%207%2E5%22%20set%2C%20unique%20elephant%20design%21%20&newitem=390&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=389&price=11.0000&description=Jasper%20and%20bone%20choker%2C%2016%22%20and%20bracelet%2C%207%2E5%20inches%2E%20PRICE%20REDUCED%21&newitem=389&invent=10'>


<img src = "images/necklaces/thumb/389.jpg"  border='4' bordercolor='black'
 
  name="img389" alt="jasper necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$11.00</font></b><br><font face="Verdana" verdana size="1">Jasper and bone choker, 16" and bracelet, 7.5 inches. PRICE REDUCED!</font><br>

<a href='detail.cfm?category=Necklaces&newitem=389&price=11.0000&description=Jasper%20and%20bone%20choker%2C%2016%22%20and%20bracelet%2C%207%2E5%20inches%2E%20PRICE%20REDUCED%21&newitem=389&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=388&price=19.5000&description=Aventurine%20%28Indian%20Jade%29%204%20strand%20necklace%2C%2017%22%2C%20round%20stones%2C%20goes%20beautifully%20with%20any%20open%20neck%20d&newitem=388&invent=10'>


<img src = "images/necklaces/thumb/388.jpg"  border='4' bordercolor='black'
 
  name="img388" alt="Jade necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$19.50</font></b><br><font face="Verdana" verdana size="1">Aventurine (Indian Jade) 4 strand necklace, 17", round stones, goes beautifully with any open neck d</font><br>

<a href='detail.cfm?category=Necklaces&newitem=388&price=19.5000&description=Aventurine%20%28Indian%20Jade%29%204%20strand%20necklace%2C%2017%22%2C%20round%20stones%2C%20goes%20beautifully%20with%20any%20open%20neck%20d&newitem=388&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=387&price=14.0000&description=Lapis%20lazuli%20with%20metal%20flower%20beads%2C%2024%22&newitem=387&invent=10'>


<img src = "images/necklaces/thumb/387.jpg"  border='4' bordercolor='black'
 
  name="img387" alt="lapis lazuli necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">Lapis lazuli with metal flower beads, 24"</font><br>

<a href='detail.cfm?category=Necklaces&newitem=387&price=14.0000&description=Lapis%20lazuli%20with%20metal%20flower%20beads%2C%2024%22&newitem=387&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Sets&newitem=386&price=22.0000&description=Jade%20and%20bone%20choker%2C%2018%22%2C%20bracelet%2C%207%2E5%22%2C%20and%20earrings%20set%20makes%20this%20a%20great%20gift%21&newitem=386&invent=10'>


<img src = "images/necklaces/thumb/386.jpg"  border='4' bordercolor='black'
 
  name="img386" alt="aventurine necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$22.00</font></b><br><font face="Verdana" verdana size="1">Jade and bone choker, 18", bracelet, 7.5", and earrings set makes this a great gift!</font><br>

<a href='detail.cfm?category=Sets&newitem=386&price=22.0000&description=Jade%20and%20bone%20choker%2C%2018%22%2C%20bracelet%2C%207%2E5%22%2C%20and%20earrings%20set%20makes%20this%20a%20great%20gift%21&newitem=386&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Sets&newitem=385&price=16.0000&description=Onyx%20and%20bone%20choker%2C%2018%20inch%2C%20bracelet%2C%207%2E5%22%2C%20and%20earrings%20set%20makes%20this%20a%20wonderful%20gift%21&newitem=385&invent=10'>


<img src = "images/necklaces/thumb/385.jpg"  border='4' bordercolor='black'
 
  name="img385" alt="onyx necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Onyx and bone choker, 18 inch, bracelet, 7.5", and earrings set makes this a wonderful gift!</font><br>

<a href='detail.cfm?category=Sets&newitem=385&price=16.0000&description=Onyx%20and%20bone%20choker%2C%2018%20inch%2C%20bracelet%2C%207%2E5%22%2C%20and%20earrings%20set%20makes%20this%20a%20wonderful%20gift%21&newitem=385&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=384&price=22.0000&description=Jasper%20choker%2C%20elephant%20design%2C%2018%22%2C%20bracelet%2C%207%2E5%20or%208%22%2C%20and%20earrings%20set%20makes%20this%20a%20wonderful%20gi&newitem=384&invent=10'>


<img src = "images/necklaces/thumb/384.jpg"  border='4' bordercolor='black'
 
  name="img384" alt="jasper necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$22.00</font></b><br><font face="Verdana" verdana size="1">Jasper choker, elephant design, 18", bracelet, 7.5 or 8", and earrings set makes this a wonderful gi</font><br>

<a href='detail.cfm?category=Necklaces&newitem=384&price=22.0000&description=Jasper%20choker%2C%20elephant%20design%2C%2018%22%2C%20bracelet%2C%207%2E5%20or%208%22%2C%20and%20earrings%20set%20makes%20this%20a%20wonderful%20gi&newitem=384&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Sets&newitem=383&price=18.0000&description=Amethyst%20choker%2C%2016%22%2C%20bracelet%208%22%2C%20and%20earrings%20set%20makes%20a%20great%20gift%21&newitem=383&invent=10'>


<img src = "images/necklaces/thumb/383.jpg"  border='4' bordercolor='black'
 
  name="img383" alt="amethyst necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Amethyst choker, 16", bracelet 8", and earrings set makes a great gift!</font><br>

<a href='detail.cfm?category=Sets&newitem=383&price=18.0000&description=Amethyst%20choker%2C%2016%22%2C%20bracelet%208%22%2C%20and%20earrings%20set%20makes%20a%20great%20gift%21&newitem=383&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Sets&newitem=382&price=16.0000&description=Mixed%20stone%20choker%2C%2016%22%2C%207%2E5%20or%208%22%20bracelet%20and%20earrings%20set%2E%20%20This%20lovely%20set%20makes%20a%20great%20gift%21%0D%0A&newitem=382&invent=10'>


<img src = "images/necklaces/thumb/382.jpg"  border='4' bordercolor='black'
 
  name="img382" alt="mixed stones necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Mixed stone choker, 16", 7.5 or 8" bracelet and earrings set.  This lovely set makes a great gift!
</font><br>

<a href='detail.cfm?category=Sets&newitem=382&price=16.0000&description=Mixed%20stone%20choker%2C%2016%22%2C%207%2E5%20or%208%22%20bracelet%20and%20earrings%20set%2E%20%20This%20lovely%20set%20makes%20a%20great%20gift%21%0D%0A&newitem=382&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Sets&newitem=381&price=18.0000&description=Carnelian%20choker%20set%2C%20choker%2C%2016%22%2C%20bracelet%207%2E5%22%20or%208%22%20You%27ll%20look%20stunning%20in%20this%20beautiful%20set%2E&newitem=381&invent=10'>


<img src = "images/necklaces/thumb/381.jpg"  border='4' bordercolor='black'
 
  name="img381" alt="carnelian necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Carnelian choker set, choker, 16", bracelet 7.5" or 8" You'll look stunning in this beautiful set.</font><br>

<a href='detail.cfm?category=Sets&newitem=381&price=18.0000&description=Carnelian%20choker%20set%2C%20choker%2C%2016%22%2C%20bracelet%207%2E5%22%20or%208%22%20You%27ll%20look%20stunning%20in%20this%20beautiful%20set%2E&newitem=381&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=sets&newitem=321&price=12.0000&description=Carnelian%20set%2C%2017in%2E%2C%20round%20stones%2E&newitem=321&invent=4'>


<img src = "images/necklaces/thumb/321.jpg"  border='4' bordercolor='black'
 
  name="img321" alt="carnelian necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Carnelian set, 17in., round stones.</font><br>

<a href='detail.cfm?category=sets&newitem=321&price=12.0000&description=Carnelian%20set%2C%2017in%2E%2C%20round%20stones%2E&newitem=321&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=sets&newitem=319&price=12.0000&description=Aventurine%20%28Indian%20jade%29%20set%2C%2017in%2E%2C%20spherical%20stones%2E&newitem=319&invent=2'>


<img src = "images/necklaces/thumb/319.jpg"  border='4' bordercolor='black'
 
  name="img319" alt="jade necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Aventurine (Indian jade) set, 17in., spherical stones.</font><br>

<a href='detail.cfm?category=sets&newitem=319&price=12.0000&description=Aventurine%20%28Indian%20jade%29%20set%2C%2017in%2E%2C%20spherical%20stones%2E&newitem=319&invent=2'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=sets&newitem=322&price=17.0000&description=Tiger%20eye%20set%20with%20golden%20rings%2C%2024in%2E%2C%20round%20stones&newitem=322&invent=6'>


<img src = "images/necklaces/thumb/322.jpg"  border='4' bordercolor='black'
 
  name="img322" alt="tiger eye necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$17.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye set with golden rings, 24in., round stones</font><br>

<a href='detail.cfm?category=sets&newitem=322&price=17.0000&description=Tiger%20eye%20set%20with%20golden%20rings%2C%2024in%2E%2C%20round%20stones&newitem=322&invent=6'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=sets&newitem=323&price=19.0000&description=Black%20tiger%20eye%20set%2C%2024in%2E%2C%20attractive%20heart%20shaped%20stones%2E&newitem=323&invent=2'>


<img src = "images/necklaces/thumb/323.jpg"  border='4' bordercolor='black'
 
  name="img323" alt="tiger eye necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$19.00</font></b><br><font face="Verdana" verdana size="1">Black tiger eye set, 24in., attractive heart shaped stones.</font><br>

<a href='detail.cfm?category=sets&newitem=323&price=19.0000&description=Black%20tiger%20eye%20set%2C%2024in%2E%2C%20attractive%20heart%20shaped%20stones%2E&newitem=323&invent=2'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=sets&newitem=326&price=16.0000&description=Lapis%20set%20with%20ethnic%20metal%20pieces%2C%2017in%2E&newitem=326&invent=2'>


<img src = "images/necklaces/thumb/326.jpg"  border='4' bordercolor='black'
 
  name="img326" alt="lapis lazuli necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Lapis set with ethnic metal pieces, 17in.</font><br>

<a href='detail.cfm?category=sets&newitem=326&price=16.0000&description=Lapis%20set%20with%20ethnic%20metal%20pieces%2C%2017in%2E&newitem=326&invent=2'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=258&price=7.0000&description=Simulated%20malachite%20with%20golden%20rings%2C%2017in%2E&newitem=258&invent=10'>


<img src = "images/necklaces/thumb/258.jpg"  border='4' bordercolor='black'
 
  name="img258" alt="malachite necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$7.00</font></b><br><font face="Verdana" verdana size="1">Simulated malachite with golden rings, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=258&price=7.0000&description=Simulated%20malachite%20with%20golden%20rings%2C%2017in%2E&newitem=258&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=252&price=14.0000&saleprice=6.5000&description=Carnelian%20and%20unique%20ethnic%20balls%2C%2017in%2E&newitem=252&invent=18'>


<img src = "images/necklaces/thumb/252.jpg"  border='4' bordercolor='black'
 
  name="img252" alt="carnelian necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$6.50</B>&nbsp;Regular
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">Carnelian and unique ethnic balls, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=252&price=14.0000&saleprice=6.5000&description=Carnelian%20and%20unique%20ethnic%20balls%2C%2017in%2E&newitem=252&invent=18'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=243&price=14.9900&description=Peridot%2C%2017in%2E&newitem=243&invent=5'>


<img src = "images/necklaces/thumb/243.jpg"  border='4' bordercolor='black'
 
  name="img243" alt="peridot necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$14.99</font></b><br><font face="Verdana" verdana size="1">Peridot, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=243&price=14.9900&description=Peridot%2C%2017in%2E&newitem=243&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=239&price=12.0000&description=Pearl%20and%20indian%20jade%20%28aventurine%29%2C%20elliptical%20stones%2C%2017in%2E&newitem=239&invent=8'>


<img src = "images/necklaces/thumb/239.jpg"  border='4' bordercolor='black'
 
  name="img239" alt="pearl, jade necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Pearl and indian jade (aventurine), elliptical stones, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=239&price=12.0000&description=Pearl%20and%20indian%20jade%20%28aventurine%29%2C%20elliptical%20stones%2C%2017in%2E&newitem=239&invent=8'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=245&price=20.0000&saleprice=16.5000&description=Pearl%20and%20simulated%20turquoise%2C%20double%20strand%20necklace%2C%2017in%2E&newitem=245&invent=7'>


<img src = "images/necklaces/thumb/245.jpg"  border='4' bordercolor='black'
 
  name="img245" alt="pearl, turquoise necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$16.50</B>&nbsp;Regular
<b><font color="#000080">$20.00</font></b><br><font face="Verdana" verdana size="1">Pearl and simulated turquoise, double strand necklace, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=245&price=20.0000&saleprice=16.5000&description=Pearl%20and%20simulated%20turquoise%2C%20double%20strand%20necklace%2C%2017in%2E&newitem=245&invent=7'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=246&price=13.0000&description=Brown%20agate%20with%20black%20inclusions%2C%2017in%2E%2E%20Beautiful%20polished%20stones%20with%20an%20attractive%20heart%20clasp%2E&newitem=246&invent=4'>


<img src = "images/necklaces/thumb/246.jpg"  border='4' bordercolor='black'
 
  name="img246" alt="bloodstone necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$13.00</font></b><br><font face="Verdana" verdana size="1">Brown agate with black inclusions, 17in.. Beautiful polished stones with an attractive heart clasp.</font><br>

<a href='detail.cfm?category=necklaces&newitem=246&price=13.0000&description=Brown%20agate%20with%20black%20inclusions%2C%2017in%2E%2E%20Beautiful%20polished%20stones%20with%20an%20attractive%20heart%20clasp%2E&newitem=246&invent=4'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=247&price=15.0000&description=Tiger%20eye%20with%20golden%20rings%2C%2024in%2E&newitem=247&invent=10'>


<img src = "images/necklaces/thumb/247.jpg"  border='4' bordercolor='black'
 
  name="img247" alt="tiger eye necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$15.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye with golden rings, 24in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=247&price=15.0000&description=Tiger%20eye%20with%20golden%20rings%2C%2024in%2E&newitem=247&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=249&price=12.0000&saleprice=7.0000&description=Tiger%20eye%20with%20golden%20rings%2C%2017in%2E&newitem=249&invent=20'>


<img src = "images/necklaces/thumb/249.jpg"  border='4' bordercolor='black'
 
  name="img249" alt="tiger eye necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$7.00</B>&nbsp;Regular
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye with golden rings, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=249&price=12.0000&saleprice=7.0000&description=Tiger%20eye%20with%20golden%20rings%2C%2017in%2E&newitem=249&invent=20'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=250&price=16.0000&saleprice=9.5000&description=Tiger%20eye%20with%20golden%20rings%2C%2024in%2E%2C%20a%20great%20cut%20to%20show%20off%20tiger%20eye%20hues&newitem=250&invent=10'>


<img src = "images/necklaces/thumb/250.jpg"  border='4' bordercolor='black'
 
  name="img250" alt="tiger eye necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$9.50</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye with golden rings, 24in., a great cut to show off tiger eye hues</font><br>

<a href='detail.cfm?category=necklaces&newitem=250&price=16.0000&saleprice=9.5000&description=Tiger%20eye%20with%20golden%20rings%2C%2024in%2E%2C%20a%20great%20cut%20to%20show%20off%20tiger%20eye%20hues&newitem=250&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=240&price=12.0000&description=Tiger%20eye%2C%20uncut%2C%2015%20in%2E&newitem=240&invent=10'>


<img src = "images/necklaces/thumb/240.jpg"  border='4' bordercolor='black'
 
  name="img240" alt="tiger eye necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Tiger eye, uncut, 15 in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=240&price=12.0000&description=Tiger%20eye%2C%20uncut%2C%2015%20in%2E&newitem=240&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=253&price=12.0000&saleprice=9.0000&description=Jasper%20with%20golden%20rings%2C%2017in%2E&newitem=253&invent=19'>


<img src = "images/necklaces/thumb/253.jpg"  border='4' bordercolor='black'
 
  name="img253" alt="jasper necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$9.00</B>&nbsp;Regular
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Jasper with golden rings, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=253&price=12.0000&saleprice=9.0000&description=Jasper%20with%20golden%20rings%2C%2017in%2E&newitem=253&invent=19'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=254&price=15.0000&saleprice=11.2500&description=Jasper%20with%20ethnic%20metal%20pieces%2C%2024in%2E&newitem=254&invent=20'>


<img src = "images/necklaces/thumb/254.jpg"  border='4' bordercolor='black'
 
  name="img254" alt="jasper necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$11.25</B>&nbsp;Regular
<b><font color="#000080">$15.00</font></b><br><font face="Verdana" verdana size="1">Jasper with ethnic metal pieces, 24in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=254&price=15.0000&saleprice=11.2500&description=Jasper%20with%20ethnic%20metal%20pieces%2C%2024in%2E&newitem=254&invent=20'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=255&price=18.0000&saleprice=13.5000&description=Garnet%20with%20unique%20polished%20agate%20pieces%2C%2017in%2E%2E%20%20A%20real%20find%21&newitem=255&invent=10'>


<img src = "images/necklaces/thumb/255.jpg"  border='4' bordercolor='black'
 
  name="img255" alt="garnet necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$13.50</B>&nbsp;Regular
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Garnet with unique polished agate pieces, 17in..  A real find!</font><br>

<a href='detail.cfm?category=necklaces&newitem=255&price=18.0000&saleprice=13.5000&description=Garnet%20with%20unique%20polished%20agate%20pieces%2C%2017in%2E%2E%20%20A%20real%20find%21&newitem=255&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=238&price=12.0000&description=Pearl%20and%20indian%20jade%20%28aventurine%29%2C%2017in%2E&newitem=238&invent=6'>


<img src = "images/necklaces/thumb/238.jpg"  border='4' bordercolor='black'
 
  name="img238" alt="pearl, jade necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$12.00</font></b><br><font face="Verdana" verdana size="1">Pearl and indian jade (aventurine), 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=238&price=12.0000&description=Pearl%20and%20indian%20jade%20%28aventurine%29%2C%2017in%2E&newitem=238&invent=6'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=257&price=11.0000&saleprice=8.2500&description=Garnet%20with%20golden%20rings%2C%2017in%2E&newitem=257&invent=20'>


<img src = "images/necklaces/thumb/257.jpg"  border='4' bordercolor='black'
 
  name="img257" alt="garnet necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$8.25</B>&nbsp;Regular
<b><font color="#000080">$11.00</font></b><br><font face="Verdana" verdana size="1">Garnet with golden rings, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=257&price=11.0000&saleprice=8.2500&description=Garnet%20with%20golden%20rings%2C%2017in%2E&newitem=257&invent=20'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=227&price=15.0000&description=Amethyst%20and%20bone%20with%20elephant%20design%2C%2016in%2E&newitem=227&invent=10'>


<img src = "images/necklaces/thumb/227.jpg"  border='4' bordercolor='black'
 
  name="img227" alt="amethyst necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$15.00</font></b><br><font face="Verdana" verdana size="1">Amethyst and bone with elephant design, 16in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=227&price=15.0000&description=Amethyst%20and%20bone%20with%20elephant%20design%2C%2016in%2E&newitem=227&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=259&price=22.0000&saleprice=10.5000&description=Simulated%20malachite%20with%20ethnic%20balls%2C%2017%20inches%2E%20Very%20pretty%20indeed%2E&newitem=259&invent=20'>


<img src = "images/necklaces/thumb/259.jpg"  border='4' bordercolor='black'
 
  name="img259" alt="malachite necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$10.50</B>&nbsp;Regular
<b><font color="#000080">$22.00</font></b><br><font face="Verdana" verdana size="1">Simulated malachite with ethnic balls, 17 inches. Very pretty indeed.</font><br>

<a href='detail.cfm?category=necklaces&newitem=259&price=22.0000&saleprice=10.5000&description=Simulated%20malachite%20with%20ethnic%20balls%2C%2017%20inches%2E%20Very%20pretty%20indeed%2E&newitem=259&invent=20'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=262&price=22.8000&description=Moss%20agate%20with%20golden%20rings%2C%2024in%2E%20%20Unique%20plant%2Dlike%20inclusions&newitem=262&invent=12'>


<img src = "images/necklaces/thumb/262.jpg"  border='4' bordercolor='black'
 
  name="img262" alt="moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$22.80</font></b><br><font face="Verdana" verdana size="1">Moss agate with golden rings, 24in.  Unique plant-like inclusions</font><br>

<a href='detail.cfm?category=necklaces&newitem=262&price=22.8000&description=Moss%20agate%20with%20golden%20rings%2C%2024in%2E%20%20Unique%20plant%2Dlike%20inclusions&newitem=262&invent=12'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=263&price=24.0000&description=Moss%20agate%20necklace%2C%2017in%2E%20%20Unique%20plant%2Dlike%20inclusions%2E&newitem=263&invent=3'>


<img src = "images/necklaces/thumb/263.jpg"  border='4' bordercolor='black'
 
  name="img263" alt="moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$24.00</font></b><br><font face="Verdana" verdana size="1">Moss agate necklace, 17in.  Unique plant-like inclusions.</font><br>

<a href='detail.cfm?category=necklaces&newitem=263&price=24.0000&description=Moss%20agate%20necklace%2C%2017in%2E%20%20Unique%20plant%2Dlike%20inclusions%2E&newitem=263&invent=3'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=264&price=22.0000&description=Moss%20Agate%2C%2024in%2E%2E%20%20Unique%203%2DD%20tear%2Ddrop%20style%2C%20an%20exquisite%20piece%21&newitem=264&invent=7'>


<img src = "images/necklaces/thumb/264.jpg"  border='4' bordercolor='black'
 
  name="img264" alt="moss agate necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$22.00</font></b><br><font face="Verdana" verdana size="1">Moss Agate, 24in..  Unique 3-D tear-drop style, an exquisite piece!</font><br>

<a href='detail.cfm?category=necklaces&newitem=264&price=22.0000&description=Moss%20Agate%2C%2024in%2E%2E%20%20Unique%203%2DD%20tear%2Ddrop%20style%2C%20an%20exquisite%20piece%21&newitem=264&invent=7'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=265&price=17.0000&description=Goldstone%20necklace%2C%2017in%2E%20with%20silver%20and%20beautiful%20sparkling%20goldstone%20pendant%2E&newitem=265&invent=8'>


<img src = "images/necklaces/thumb/265.jpg"  border='4' bordercolor='black'
 
  name="img265" alt="goldstone necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$17.00</font></b><br><font face="Verdana" verdana size="1">Goldstone necklace, 17in. with silver and beautiful sparkling goldstone pendant.</font><br>

<a href='detail.cfm?category=necklaces&newitem=265&price=17.0000&description=Goldstone%20necklace%2C%2017in%2E%20with%20silver%20and%20beautiful%20sparkling%20goldstone%20pendant%2E&newitem=265&invent=8'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=266&price=16.0000&saleprice=12.0000&description=Goldstone%20with%20golden%20rings%2C%2024in%2E&newitem=266&invent=20'>


<img src = "images/necklaces/thumb/266.jpg"  border='4' bordercolor='black'
 
  name="img266" alt="goldstone necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$12.00</B>&nbsp;Regular
<b><font color="#000080">$16.00</font></b><br><font face="Verdana" verdana size="1">Goldstone with golden rings, 24in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=266&price=16.0000&saleprice=12.0000&description=Goldstone%20with%20golden%20rings%2C%2024in%2E&newitem=266&invent=20'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=256&price=18.0000&saleprice=13.5000&description=Garnet%20with%20unique%20agate%20pieces%2C%2017in%2E%20%20%20A%20real%20find%21&newitem=256&invent=10'>


<img src = "images/necklaces/thumb/256.jpg"  border='4' bordercolor='black'
 
  name="img256" alt="garnet necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$13.50</B>&nbsp;Regular
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Garnet with unique agate pieces, 17in.   A real find!</font><br>

<a href='detail.cfm?category=necklaces&newitem=256&price=18.0000&saleprice=13.5000&description=Garnet%20with%20unique%20agate%20pieces%2C%2017in%2E%20%20%20A%20real%20find%21&newitem=256&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=217&price=22.0000&saleprice=15.0000&description=Garnet%20necklace%2C%20double%20strand%2C%2017in%2E&newitem=217&invent=5'>


<img src = "images/necklaces/thumb/217.jpg"  border='4' bordercolor='black'
 
  name="img217" alt="garnet necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$15.00</B>&nbsp;Regular
<b><font color="#000080">$22.00</font></b><br><font face="Verdana" verdana size="1">Garnet necklace, double strand, 17in.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=217&price=22.0000&saleprice=15.0000&description=Garnet%20necklace%2C%20double%20strand%2C%2017in%2E&newitem=217&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=267&price=28.0000&description=Smoky%20quartz%2C%2024in%2E%20%20Unique%203%2DD%20tear%2Ddrop%20style%2C%20an%20exquisite%20piece%21&newitem=267&invent=7'>


<img src = "images/necklaces/thumb/267.jpg"  border='4' bordercolor='black'
 
  name="img267" alt="smoky quartz necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$28.00</font></b><br><font face="Verdana" verdana size="1">Smoky quartz, 24in.  Unique 3-D tear-drop style, an exquisite piece!</font><br>

<a href='detail.cfm?category=necklaces&newitem=267&price=28.0000&description=Smoky%20quartz%2C%2024in%2E%20%20Unique%203%2DD%20tear%2Ddrop%20style%2C%20an%20exquisite%20piece%21&newitem=267&invent=7'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=necklaces&newitem=177&price=10.0000&saleprice=7.5000&description=Aventurine%20%28Indian%20jade%29%2C%20square%20stones%20with%20golden%20rings%2C%2017in%2E&newitem=177&invent=10'>


<img src = "images/necklaces/thumb/177.jpg"  border='4' bordercolor='black'
 
  name="img177" alt="jade necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$7.50</B>&nbsp;Regular
<b><font color="#000080">$10.00</font></b><br><font face="Verdana" verdana size="1">Aventurine (Indian jade), square stones with golden rings, 17in.</font><br>

<a href='detail.cfm?category=necklaces&newitem=177&price=10.0000&saleprice=7.5000&description=Aventurine%20%28Indian%20jade%29%2C%20square%20stones%20with%20golden%20rings%2C%2017in%2E&newitem=177&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=207&price=14.0000&description=Lapis%2C%20oxidized%2C%20fancy%20cut%2C%20with%20ethnic%20metal%20pieces%2C%2017in%2E&newitem=207&invent=9'>


<img src = "images/necklaces/thumb/207.jpg"  border='4' bordercolor='black'
 
  name="img207" alt="lapis lazuli necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$14.00</font></b><br><font face="Verdana" verdana size="1">Lapis, oxidized, fancy cut, with ethnic metal pieces, 17in.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=207&price=14.0000&description=Lapis%2C%20oxidized%2C%20fancy%20cut%2C%20with%20ethnic%20metal%20pieces%2C%2017in%2E&newitem=207&invent=9'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=208&price=11.0000&saleprice=9.0000&description=Pearl%20and%20goldstone%2C%20elliptical%20stones%2C%2017in%2E&newitem=208&invent=6'>


<img src = "images/necklaces/thumb/208.jpg"  border='4' bordercolor='black'
 
  name="img208" alt="pearl, goldstone necklaces"></a><br><font verdana size='1'><img src=images/sale.gif><B>$9.00</B>&nbsp;Regular
<b><font color="#000080">$11.00</font></b><br><font face="Verdana" verdana size="1">Pearl and goldstone, elliptical stones, 17in.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=208&price=11.0000&saleprice=9.0000&description=Pearl%20and%20goldstone%2C%20elliptical%20stones%2C%2017in%2E&newitem=208&invent=6'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=210&price=18.0000&description=Pearl%20and%20diamond%20cut%20lapis%20stones%2C%2017in%2E&newitem=210&invent=10'>


<img src = "images/necklaces/thumb/210.jpg"  border='4' bordercolor='black'
 
  name="img210" alt="pearl, lapis necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$18.00</font></b><br><font face="Verdana" verdana size="1">Pearl and diamond cut lapis stones, 17in.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=210&price=18.0000&description=Pearl%20and%20diamond%20cut%20lapis%20stones%2C%2017in%2E&newitem=210&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=211&price=25.0000&description=Pearl%20and%20shaded%20pearl%20necklace%2C%20double%20strand%2C%2017in%2E&newitem=211&invent=5'>


<img src = "images/necklaces/thumb/211.jpg"  border='4' bordercolor='black'
 
  name="img211" alt="pearl necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$25.00</font></b><br><font face="Verdana" verdana size="1">Pearl and shaded pearl necklace, double strand, 17in.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=211&price=25.0000&description=Pearl%20and%20shaded%20pearl%20necklace%2C%20double%20strand%2C%2017in%2E&newitem=211&invent=5'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>




<td valign=top align='center' border=0>

<a href='detail.cfm?category=Necklaces&newitem=212&price=26.0000&description=Amethyst%20necklace%2C%20button%20shaped%20clear%20light%20purple%20stones%2C%20good%20quality%2C%2024in%2E&newitem=212&invent=10'>


<img src = "images/necklaces/thumb/212.jpg"  border='4' bordercolor='black'
 
  name="img212" alt="amethyst necklaces"></a><br><font verdana size='1'>
<b><font color="#000080">$26.00</font></b><br><font face="Verdana" verdana size="1">Amethyst necklace, button shaped clear light purple stones, good quality, 24in.</font><br>

<a href='detail.cfm?category=Necklaces&newitem=212&price=26.0000&description=Amethyst%20necklace%2C%20button%20shaped%20clear%20light%20purple%20stones%2C%20good%20quality%2C%2024in%2E&newitem=212&invent=10'>

<font verdana size='2'><b>Zoom/Detail</b></font></a>&nbsp;</font>

	</td>


	
	</tr></table>
<Table cellpadding=10 cellspacing=0 border='0' width="750"><tr width=750 bgcolor="white" valign="top">



</b>
</font>
</tr></table>
  


